GET http://localhost:5000/api/products/b531da18-52cf-4d91-be45-c28f2a98115f



###
GET http://localhost:5000/api/chains/chain/100

###
GET http://localhost:5000/api/cities

### 
POST http://localhost:5000/api/products
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
    "title": "Toinen jalkapallo",
    "description": "Vähän potkittu jalkapallo",
    "image": "https://www.vastavalo.net/albums/userpics/22294/normal_p8172409pt.jpg",
    "price": 1545.5,
    "owner": "b531da18-52cf-4d91-be45-c28f2a98115f"
  }
###
POST http://localhost:5000/api/cities
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "capital": "Maputo",
  "country": "Mozabique",
  "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRG-GoIlmsdgP7Br6Une5WtzDo8MTeA5D6kh7LUgHpkaQ&s"
}

### 
DELETE http://localhost:5000/api/cities/4
Authorization: BEARER {{authToken}}

###
POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
  "name": "Tony Stark Wayne",
  "email": "tony@stark.com",
  "password": "password1234"
}


###
 # @name login
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "tony@stark1.com",
  "password": "password1234"
}

###
@authToken = {{login.response.body.token}}